export { default as LandingPage } from "./Home";
export { default as Leads } from "./Leads";
export { default as Contacts } from "./Contacts";
export { default as Sales } from "./Sales";
export { default as Companies } from "./Companies";
export { default as Integrations } from "./Integrations";
export { default as Tasks } from "./Tasks";
export { default as Settings } from "./Settings";
export { default as Invoices } from "./Invoices";